version: '3'

networks:
  nginx-php74-mysql8
services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql8-service
    networks:
      - nginx-php74-mysql8
  #php
  php74-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php74-container
    ports:
      - '9000:9000'
    volumes:
      - ./app/:/var/www/project
    networks:
      - nginx-php74-mysql8

  #mysql
  mysql8-service:

  #node

